name: web_worker_channel
description: >
  Experimental Web Workers with JS-Interop
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/web_worker_channel

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  js: ^0.6.1
  stream_channel: ^1.6.4

dev_dependencies:
  build_runner: ^0.8.7
  build_test: ^0.10.2+2
  build_web_compilers: ^0.3.7+3
  test: ^0.12.35
